# Generated by Django 4.0.1 on 2022-07-11 12:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0004_remove_task_tags_task_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 7, 11, 17, 43, 20, 178133)),
        ),
        migrations.AlterField(
            model_name='task',
            name='tags',
            field=models.ManyToManyField(to='to_do.Tag'),
        ),
    ]
